force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = false
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Upper"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_arm_blocks = true
match_block_trailing_comma = true
newline_style = "Unix"
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
